// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var times = Caml_int32.imul;

function square(x) {
  return Caml_int32.imul(x, x);
}

var Tools = /* module */[
  /* times */times,
  /* square */square
];

var $$Math = /* module */[/* Tools */Tools];

Pervasives.print_string("Result: ");

Pervasives.print_int(16);

Pervasives.print_newline(/* () */0);

exports.$$Math = $$Math;
/*  Not a pure module */
